input {
  beats {
    port => "5044"
  }
}
filter {
  mutate {
  }
}
output {
  elasticsearch {
    hosts => "http://elasticsearch:9200"
    index => "logslab4"

  }
  stdout { codec => rubydebug }

}