services:
  logstash:
    image: logstash:9.1.5
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      XPACK_MONITORING_ENABLED: "false"
    volumes:
      - ../logs:/usr/share/logstash/logs
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
    - elastic

networks:
  elastic:
    external:: true

  