input {
  beats {
    port => 5044
  }
}
filter {
  mutate {
    add_field => { "received_from" => "filebeat" }
  }
}
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs"

  }
  stdout { }

}