services:
  nginx:
    image: nginx:latest
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - gateway

networks:
  gateway:
    external: true

  