services:
  service2:
    build: ./
    container_name: service2
    ports:
      - "5002:5002"
    volumes:
        - ../logs:/src/logs
    networks:
      - gateway

networks:
  gateway:
    external: true

volumes:
    elasticsearch_data:
        driver: local

  